version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_tracker_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_tracker
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: